#!/usr/bin/with-contenv bash

# Ensure required devices are created
if [ ! -e /dev/kvm ]; then
    mknod /dev/kvm c 10 $(grep '\<kvm\>' /proc/misc | cut -f 1 -d' ')
    chown :kvm /dev/kvm
    chmod g+w /dev/kvm
fi

if [ ! -e /dev/net/tun ]; then
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 $(grep '\<tun\>' /proc/misc | cut -f 1 -d' ')
    chmod 666 /dev/net/tun
fi

# Prepare to start gns3server as gns3 user
HOME=/opt/gns3
USER=abc
GROUP=abc

# Fix permissions
chown -R ${USER}:${GROUP} ${HOME}

# Start gns3server
exec \
    sudo -u abc /usr/local/bin/gns3server
